### ISSUE TITLE
Support UNC paths

### ISSUE THREAD

**Issue by thomaslevesque** [peteraritchie/LongPath#9]
`Path.GetPathRoot(@"\\server\foo\bar\baz.txt")` should return `\\server\foo`, but it returns `\\` instead

**Comment by jonathanjones2** [comment]
Have you decided if you'll be extending support to UNC paths? I'm currently in a situation where I scan shares via the UNC path and I'm running into issues with long paths and filenames.

**Comment by peteraritchie** [comment]
I believe the latest changes and passing tests mean that UNCs are now supported.  I would appreciate if someone could try out some of the issues they've ad with UNCs prior.

Thanks.

**Comment by FuchsiaSoft** [comment]
@peteraritchie are you still wanting results?... I'm about to use this for a lot of work with UNCs so can let you know how it goes in a week or so?

**Comment by jonathanjones2** [comment]
No thanks

JJ

**Comment by FuchsiaSoft** [comment]
JJ I was referencing Peter's comment after yours. Sorry if I was unclear.

**Comment by peteraritchie** [comment]
@FuchsiaSoft yeah, the code should work now with UNCs; I haven't had the time to get too deep into testing it (moved to a different country :) ).  If there's something blocking you, let me know.

**Comment by idiamant** [comment]
Hi,
I am having a problem with the UNC support.
I have the following path in a variable: \\10.24.0.11\Deployments\Backups\AndroidBuilder

That directory exists, but when checking with Directory.Exists("\\10.24.0.11\Deployments\Backups\AndroidBuilder") it doesn't find this path.
Then it goes into the next line, which is Directory.CreateDirectory("\\10.24.0.11\Deployments\Backups\AndroidBuilder"), and this one fails due to this error: {"The UNC path should be of the form \\\\server\\share."}.

Obviously there is lack of UNC support, and I couldn't fully understand why it fails.

Would love to get assistance with this one.

Thanks,
Ido

**Comment by peteraritchie** [comment]
I'm not clear on your question. "\10.24.0.11\Deployments\Backups\AndroidBuilder" is not a valid UNC.  UNCs must start with "\\", which is what is detailed in the error.

**Comment by idiamant** [comment]
yea, sorry, it was a wrong Paste. it is \\10.24.0.11\...

**Comment by peteraritchie** [comment]
Huh? that's still missing a slash

**Comment by idiamant** [comment]
ahhhh
for some reason github removes double slashes :)
its \\\\10.24.0.11\\deployments\\

**Comment by enoshixi** [comment]
UNC paths aren't working for me either.  I think the problem is that the long path format for UNC paths is a little different... `\\server\share` should be formatted as `\\?\UNC\server\share`.

**Comment by gpetrou** [comment]
Are you planning to check the PR for the UNC paths? Also, are you planning to release a new version?

**Comment by NeilWhitworth** [comment]
I have been testing with pull request #27 and it does seam to work for long UNC paths. The only issue I has was a path that was exactly MAXPATH in length

**Comment by peteraritchie** [comment]
@NeilWhitworth What issue did you have with a path that was exactly MAXPATH?

**Comment by peteraritchie** [comment]
Assuming this is working now
